// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantReview;

namespace RestaurantReview.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20200617185942_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestaurantReview.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Great pizza place",
                            LinkDescription = "Donatos Image",
                            LinkImage = "./images/Donatos-Pizza-restaurant-1200x900.jpg",
                            LinkUrl = "https://www.donatos.com",
                            Name = "Donato's"
                        },
                        new
                        {
                            Id = 2,
                            Details = "Like chipotle but 10x better",
                            LinkDescription = "Agave Image",
                            LinkImage = "./images/agave.jpg",
                            LinkUrl = "https://www.facebook.com/agaveburritobar/",
                            Name = "Agave"
                        },
                        new
                        {
                            Id = 3,
                            Details = "Really great seafood",
                            LinkDescription = "Pier W Image",
                            LinkImage = "./images/pierW.jpg",
                            LinkUrl = "http://pierw.com/",
                            Name = "Pier W"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
