// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantReview;

namespace RestaurantReview.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20200623155709_ChangedRestaurantDetailsAndReviews")]
    partial class ChangedRestaurantDetailsAndReviews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestaurantReview.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Donatos is a family-owned pizza company famous for Edge to Edge® toppings on a crispy golden thin crust. Founded in Columbus, Ohio in 1963, we take pride in giving back in every community we serve.",
                            LinkDescription = "Donatos Image",
                            LinkImage = "./images/Donatos-Pizza-restaurant-1200x900.jpg",
                            LinkUrl = "https://www.donatos.com",
                            Name = "Donato's"
                        },
                        new
                        {
                            Id = 2,
                            Details = "An Oberlin staple since 2003, Agave is the spot for fresh Mexi-Cali quick-serve cuisine, exceptional margaritas and draft beer!",
                            LinkDescription = "Agave Image",
                            LinkImage = "./images/agave.jpg",
                            LinkUrl = "https://www.facebook.com/agaveburritobar/",
                            Name = "Agave"
                        },
                        new
                        {
                            Id = 3,
                            Details = "Pier W is a landmark restaurant that has been Cleveland's premier destination for five-star dining, fresh seafood and fine wines since 1965.",
                            LinkDescription = "Pier W Image",
                            LinkImage = "./images/pierW.jpg",
                            LinkUrl = "http://pierw.com/",
                            Name = "Pier W"
                        });
                });

            modelBuilder.Entity("RestaurantReview.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Pepporoni Pizza is awesome. The lady at the counter was great! She tossed in some extra breadsticks because they were honoring the community that day! Thanks again Donato's i'll be back!!!",
                            Creator = "Bernard",
                            RestaurantId = 1,
                            ReviewDate = new DateTime(2020, 6, 23, 11, 57, 8, 618, DateTimeKind.Local).AddTicks(9588)
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Whether you are traveling thru Ohio, or you live here, you have to try Donatos Pizza!Last year, I gave up on pizza, as I found all the chains to be measly with their veggies, heavy on the salt, and not so fresh. But now that I've eaten Donatos, I've changed my mind completely. Tho I order my pizza as 'takeout', the store had a nice eating area with booths. It was very clean and tidy, and it offers salads and sides. Wholesome atmosphere.",
                            Creator = "Brenda",
                            RestaurantId = 1,
                            ReviewDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Hopefully the previous comments got this place in 5 star shape because I just ordered for the first time and it is delicious! I ordered a large create your own with well done instructions and it came early and perfectly done. Glad I gave them a chance. The delivery gal was super friendly too!",
                            Creator = "Corey",
                            RestaurantId = 1,
                            ReviewDate = new DateTime(2020, 6, 23, 11, 57, 8, 625, DateTimeKind.Local).AddTicks(7112)
                        },
                        new
                        {
                            Id = 4,
                            Comment = "We were in town from out of state and decided to stop in for dinner. Fun atmosphere, amazing food and drinks ( loved the Pink Dragon!) I would definitely come back if I’m ever in the area. The 2 people working there were very friendly and did their job well and with smiles on their faces adding to the great atmosphere!",
                            Creator = "Laurie",
                            RestaurantId = 2,
                            ReviewDate = new DateTime(2020, 6, 23, 11, 57, 8, 625, DateTimeKind.Local).AddTicks(7226)
                        },
                        new
                        {
                            Id = 5,
                            Comment = "This place might have ruined Chipotle for me. The food here is so amazing I don’t want any Mexican anywhere else again!",
                            Creator = "Jay",
                            RestaurantId = 2,
                            ReviewDate = new DateTime(2020, 6, 23, 11, 57, 8, 625, DateTimeKind.Local).AddTicks(7248)
                        },
                        new
                        {
                            Id = 6,
                            Comment = "We love Agave! Very family friendly, great prices, great food and nice staff! Highly recommend their queso and chips! This is a fast casual type of restaurant.",
                            Creator = "Josh",
                            RestaurantId = 2,
                            ReviewDate = new DateTime(2020, 6, 23, 11, 57, 8, 625, DateTimeKind.Local).AddTicks(7265)
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Surprisingly, there are not many Cleveland restaurants with a good lake view, but Pier W has the best. Plus, the selections of meals for lunch are outstanding. The service was excellent and meals reasonable and filling. We enjoyed perch, salmon, scallops, The lobster bisque and manilla clam chowder were equally tasty. Our guests left satisfied and impressed with their visit to Lakewood and Pier W.",
                            Creator = "Corey",
                            RestaurantId = 3,
                            ReviewDate = new DateTime(2020, 6, 23, 11, 57, 8, 625, DateTimeKind.Local).AddTicks(7282)
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Ventured to Pier W for dinner on our 22nd wedding anniversary. We were seated quickly with a waterview despite our running late. Our server was polite, knowledgeable & helpful. Our ceviche appetizer was just so-so, but the lobster bisque was delicious. Our dinners consisted of lobster pappardelle & bouillabaisse. The lobster pappardelle was done in a cream sauce that was well- balanced. The bouillabaisse was outstanding; loaded with scallops, muscles, shrimp, scallops & fish. The accompanying broth was fantastic & didn't overpower the seafood. We received a complimentary cheesecake for our anniversary that was very good & the wife took a serving of Buttercake home for good measure... and the next morning's snack.",
                            Creator = "John",
                            RestaurantId = 3,
                            ReviewDate = new DateTime(2020, 6, 23, 11, 57, 8, 625, DateTimeKind.Local).AddTicks(7298)
                        },
                        new
                        {
                            Id = 9,
                            Comment = "I am one who doesn't complain, but when I went to Pier W I witnessed an injustice that ruined my whole experience there. I witnessed the general manager. Scream at and berate a poor teenage busser for not moving a chair down to a table fast enough for his liking. Then the man noticed us watching him. He approached our table right by the stars. My girlfriend and I felt awkward after seeing this man throw a tempertantrum, come up to us calmly and ask us how our dinner is going. After a awkward conversation that lasted way to long with him, he walked away. 20 mins after he was screaming at someone in his headset. Nice restaurant, bad manager!!!",
                            Creator = "Dakota",
                            RestaurantId = 3,
                            ReviewDate = new DateTime(2020, 6, 23, 11, 57, 8, 625, DateTimeKind.Local).AddTicks(7314)
                        });
                });

            modelBuilder.Entity("RestaurantReview.Models.Review", b =>
                {
                    b.HasOne("RestaurantReview.Models.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
